### ISSUE TITLE
Copyrighted assets in repo

### ISSUE THREAD

**Issue by The-MAZZTer** [aldonunez/zelda1-disassembly#1]
It looks like all assets are included in this repo which could make this vulnerable to takedown.

Compare to the SM64 decompilation repo which requires the user to provide the original ROM which it extracts the assets out of..

https://github.com/n64decomp/sm64

I would suggest looking into this approach.

I submitted this based on this reddit command: https://www.reddit.com/r/emulation/comments/lgzq7y/complete_disassembly_of_nes_the_legend_of_zelda/gmursri/

**Comment by aldonunez** [comment]
I had seen Disch's disassembly of Final Fantasy, which includes the binary data, and thought there was no problem. Admittedly, it was only one sample to look at.

Anyway, I made the following changes:
- deleted the files src/dat/*.dat
- made the build script extract binary files from the ROM
- made the emu2asm tool write an entry to bins.xml every time it would write a dat file

Thank you for the suggestion.

**Comment by Newbytee** [comment]
I wouldn't consider this closed. The binaries still exist in the repository's history. What you can do it rebase and force-push (generally not something you should do to the master branch, but I'd argue this is an exceptional case).
